### ISSUE TITLE
Load libraries for SqlRender and Database Connector

### ISSUE THREAD

**Issue by jduke99** [OHDSI/OhdsiStudy2#2]
Needed to manually load library for DatabaseConnector.   Would put back into MainAnalysis.R

install_github("ohdsi/SqlRender")
install_github("ohdsi/DatabaseConnector")

library(SqlRender)
library(DatabaseConnector)

**Comment by msuchard** [comment]
R packages should not use library() explicitly.  Dependencies should be handled via DESCRIPTION and NAMESPACE.   Oddly, install_github() should handle these dependencies ... (install via CRAN certainly does).  I'll try to look into this.

**Comment by msuchard** [comment]
Closed with 77b12970e05d7a1a4f8482e1d50bba90d1384e95
