### ISSUE TITLE
Possible to Zip before sending?

### ISSUE THREAD

**Issue by jduke99** [OHDSI/OhdsiStudy2#3]
We're getting some pretty big CSV files from this study, so need to manually zip before sending.  Not a big deal of course, but if it's an easy thing for R to do, would be a good enhancement to have a **zip** parameter on the _email_ function.

Just a nice to have, definitely not a high priority issue.

**Comment by msuchard** [comment]
Implemented in 77615fa352b244de068c1c2b1075908527aa7195.
